server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-events
      authentication-database: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: combat-events-queue
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 5

video-parser-service:
  base-url: http://localhost:8081
  query-path: /api/documents
